#!/usr/bin/env bash
# Copy the parts of metawork-ontology the plugin needs into lib/ontology/vendor/.
#
#   scripts/sync-ontology.sh <path-to-metawork-ontology-checkout>
#
# Used by .github/workflows/sync-ontology.yml and by hand. Copies every
# shapes/*.ttl (not a fixed list) so a new shape upstream reaches the plugin
# on the next sync without changing this script. See docs/adr/0008.
set -euo pipefail

SRC="${1:?usage: scripts/sync-ontology.sh <metawork-ontology checkout>}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/lib/ontology/vendor"

for required in tools/metawork_ontology.py ontology/metawork.ttl shapes requirements.txt LICENSE.md; do
  [ -e "$SRC/$required" ] || { echo "sync-ontology: $SRC/$required not found" >&2; exit 1; }
done

rm -rf "$DEST"
mkdir -p "$DEST/tools" "$DEST/ontology" "$DEST/shapes"
cp "$SRC/tools/metawork_ontology.py" "$DEST/tools/"
cp "$SRC/ontology/"*.ttl "$DEST/ontology/"
cp "$SRC/shapes/"*.ttl "$DEST/shapes/"
cp "$SRC/requirements.txt" "$SRC/LICENSE.md" "$DEST/"

SHA="$(git -C "$SRC" rev-parse HEAD 2>/dev/null || echo unknown)"
cat > "$DEST/SNAPSHOT.md" <<SNAP
# lib/ontology/vendor/ snapshot

Generated by \`scripts/sync-ontology.sh\` (run by
\`.github/workflows/sync-ontology.yml\`). Do not hand-edit files here; edits
are overwritten on the next sync. Change them in
[\`Integral-Productivity/metawork-ontology\`](https://github.com/Integral-Productivity/metawork-ontology)
instead.

Source: \`Integral-Productivity/metawork-ontology@${SHA:0:7}\`
(full SHA: \`${SHA}\`)

Licensing follows the source repo's \`LICENSE.md\` (copied alongside):
\`ontology/\` and \`shapes/\` are CC-BY-SA-4.0; \`tools/\` is MIT.
SNAP

echo "sync-ontology: vendored metawork-ontology@${SHA:0:7} into lib/ontology/vendor/"
